# test.yml
name: test

on: 
  push:
    branches: [ test ]

jobs:
  deploy:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: excuting remote ssh commands
        uses: actions/checkout@v2
        with:
          host: 3.34.52.238
          username: ubuntu
          key: key-0cd45621cd28141a5
          port: 22
          script: |
            cd /home/ubuntu/Server-V2
            git pull origin dev
            pm2 kill
            npm i --force
            npm run build
            pm2 start dist/main.js
